version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-demo-container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./fastapi_demo.db:/app/fastapi_demo.db  
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
